DROP TABLE IF EXISTS ingressos;
DROP TABLE IF EXISTS poltronas;
DROP TABLE IF EXISTS sessoes;
DROP TABLE IF EXISTS salas;
DROP TABLE IF EXISTS filmes;
DROP TABLE IF EXISTS cliente;

CREATE TABLE IF NOT EXISTS cliente (
    cpf VARCHAR(14) PRIMARY KEY,
    nome_cliente VARCHAR(100) NOT NULL,
    idade int NOT NULL
);

CREATE TABLE IF NOT EXISTS filmes (
    id INT(11) PRIMARY KEY AUTO_INCREMENT,
    titulo VARCHAR(255) NOT NULL,
    duracao DOUBLE NOT NULL,
    genero VARCHAR(255) NOT NULL,
    updatedAt timestamp(0) NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS salas (
    id INT(11) PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(255) NOT NULL,
    total_assentos INT(11) NOT NULL
);

CREATE TABLE IF NOT EXISTS sessoes (
    id INT(11) PRIMARY KEY AUTO_INCREMENT,
    filme_id INT(11) NOT NULL,
    sala_id INT(11) NOT NULL,
    horario_inicio DATETIME NOT NULL,
    updatedAt timestamp(0) NULL DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS poltronas (
    id INT(11) PRIMARY KEY AUTO_INCREMENT,
    sala_id INT(11) NOT NULL,
    numero_poltrona VARCHAR(10) NOT NULL,
    status_poltrona ENUM('OCUPADA', 'DESOCUPADA') NOT NULL DEFAULT 'DESOCUPADA'
);

CREATE TABLE IF NOT EXISTS ingressos (
    id INT(11) PRIMARY KEY AUTO_INCREMENT,
    sessao_id INT(11) NOT NULL,
    poltrona_id INT(11) NOT NULL,
    cpf_cliente VARCHAR(14) NOT NULL
);

